// actionTypes.ts
export const GET_AMORTIZATION_ITEMS = 'GET_AMORTIZATION_ITEMS';
export const UPDATE_LOAN_DETAILS = 'UPDATE_LOAN_DETAILS';
export const UPDATE_AMORTIZATION_ITEM = 'UPDATE_AMORTIZATION_ITEM';
