// actionTypes.ts
export const GET_AMORTIZATION_ITEMS = 'GET_AMORTIZATION_ITEMS';
export const UPDATE_LOAN_DETAILS = 'UPDATE_LOAN_DETAILS';
export const UPDATE_AMORTIZATION_ITEM = 'UPDATE_AMORTIZATION_ITEM';
export const SAVE_STATE = 'SAVE_STATE';
export const GET_STATE = 'GET_STATE';
export const RESET_AMORTIZATION = 'RESET_AMORTIZATION';
